/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GlobOptions {
  exclude?: Array<string>
  cwd?: string
}
export declare function globSync(patterns: string | Array<string>, options?: GlobOptions | undefined | null): Array<string>
export declare function glob(patterns: string | Array<string>, options?: GlobOptions | undefined | null): Promise<Array<string>>
