[package]
edition = "2021"
name = "rust-gear-glob"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["tokio_rt"] }
napi-derive = "2.12.2"
globset = "0.4"
ignore = "0.4"
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
napi-build = "2.0.1"
